#version: '3'
#
#services:
#  web:
#    container_name: web-hotel-san-cristobal
#    restart: always
#    image: openjdk:17
#    ports:
#      - "80:80"
#    volumes:
#      - /home/admin/HotelSanCristobal-0.0.1-SNAPSHOT.jar:/app/HotelSanCristobal-0.0.1-SNAPSHOT.jar
#    working_dir: /app
#    command: ["java", "-jar", "HotelSanCristobal-0.0.1-SNAPSHOT.jar"]
#

version: '3'

services:
  web:
    container_name: web-hotel-san-cristobal
    restart: always
    image: openjdk:17
    ports:
      - "443:443"  # Cambiamos el puerto a 443 para HTTPS
    volumes:
      - /etc/ssl/certs/certificado.p12:/app/certificado.p12  # Montar el certificado PKCS12
      - /home/admin/HotelSanCristobal-0.0.1-SNAPSHOT.jar:/app/HotelSanCristobal-0.0.1-SNAPSHOT.jar

    working_dir: /app
    command: ["java", "-jar", "HotelSanCristobal-0.0.1-SNAPSHOT.jar"]
