version: '3.7'

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile_rasa
    container_name: my_rasa_server
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
    networks:
      - rasa_network

  action_server:
    build:
      context: .
      dockerfile: Dockerfile_actions
    container_name: my_rasa_actions
    ports:
      - "5055:5055"
    volumes:
      - /home/alexander/actions:/app/actions
    networks:
      - rasa_network

networks:
  rasa_network:
    driver: bridge
