version: '3.9'

services:
  mysql:
    image: mysql
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EwYNY0Dvz6bst3vI
      MYSQL_DATABASE: hotelSanCristobal
      MYSQL_USER: admin
      MYSQL_PASSWORD: EwYNY0Dvz6bst3vI
    ports:
      - "3306:3306"
    volumes:
      - /home/alexander/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:



