version: '3.7'

services:
  action_server:
    build:
      context: .
      dockerfile: dockerfile_actions
    container_name: my_rasa_actions
    restart: always
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    networks:
      - rasa_network
networks:
  rasa_network:
    driver: bridge