FROM nginx

# Establece el directorio de trabajo en el contenedor como /app
WORKDIR /app

# Copiar el certificado SSL/TLS al contenedor
COPY certificado.p12 /app/certificado.p12

# Copia el archivo de configuración de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer puerto 443 para HTTPS
EXPOSE 443
