# Usar la imagen oficial de Python 3.7 como base
#FROM python:3.7
#
## Directorio de trabajo en el contenedor
#WORKDIR /app
#
## Instalar las dependencias necesarias para el servidor de acciones
#RUN pip install --no-cache-dir rasa==2.8.17 mysql-connector-python
#
## Copiar el resto de los archivos al contenedor
##COPY . /app/
#
## Comando para ejecutar el servidor de acciones
##CMD ["rasa", "run", "actions", "--actions", "actions"]



# Usa una imagen base de Python oficial
FROM python:3.7

# Establece el directorio de trabajo en el contenedor como /app
WORKDIR /app

# Copia los contenidos del directorio actual en el sistema host al contenedor en /app
#COPY . /app
COPY actions /app/actions

# Instala las dependencias necesarias especificadas en requirements.txt
RUN pip install --no-cache-dir --upgrade pip rasa==2.8.17 mysql-connector-python

# Expone el puerto en el que se ejecuta la aplicación
EXPOSE 5055

# Ejecuta el servidor de acciones
CMD ["rasa", "run", "actions", "--actions", "actions"]

